name: build-backend

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JVM_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # SBT
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt/launchers
            ~/.sbt/boot
            ~/.sbt/preloaded
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/plugins.sbt', '**/build.properties') }}

      # Build
      - name: SBT Build
        run: |
          sbt \
            "all scalafmtCheckAll" \
            "all scalafixAll --check" \
            "all compile" \
            "all test" \
            "all IntegrationTest / test"
