name: Scala Steward

on:
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-id: ${{ secrets.SCALA_STEWARD_APP_ID }}
          github-app-installation-id: ${{ secrets.SCALA_STEWARD_APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
          ignore-opts-files: false
